/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-11-15 03:35:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Models.Usuario;
import javax.servlet.http.HttpSession;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("Models.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 

	session = request.getSession(false);
	if(session == null || session.getAttribute("name") == null){
		response.sendRedirect("./login.jsp");
	}





      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("\r\n");
      out.write("    <title>Economiza</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/user.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/index.css\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\" />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin />\r\n");
      out.write("    <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css2?family=Anek+Tamil:wght@100;200;300;400&family=Lato:wght@400;700&family=Poppins:wght@100;200;300;400;500;600&family=Roboto:wght@100;300&display=swap\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("    <header id=\"home\">\r\n");
      out.write("      <nav class=\"navbar navbar-expand-md py-3 menu\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <a href=\"../index.html\" class=\"btn fs-2\" data-bs-toggle=\"button\">\r\n");
      out.write("            <i class=\"bi bi-caret-left-fill fs-3\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"navbar-brand logo\" href=\"../index.jsp\">Economiza</a>\r\n");
      out.write("          <button\r\n");
      out.write("            class=\"navbar-toggler\"\r\n");
      out.write("            type=\"button\"\r\n");
      out.write("            data-bs-toggle=\"collapse\"\r\n");
      out.write("            data-bs-target=\"#menuNavbar\"\r\n");
      out.write("          >\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"collapse navbar-collapse justify-content-center\"\r\n");
      out.write("            id=\"menuNavbar\"\r\n");
      out.write("            toggle=\"collapse\"\r\n");
      out.write("            data-target=\".navbar-collapse\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"navbar-nav ms-auto itens\">\r\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"../index.jsp\"\r\n");
      out.write("                >Início</a\r\n");
      out.write("              >\r\n");
      out.write("              <a class=\"nav-link\" aria-current=\"page\" href=\"#sobre\">Sobre</a>\r\n");
      out.write("              <a class=\"nav-link\" aria-current=\"page\" href=\"#contato\"\r\n");
      out.write("                >Contatos</a\r\n");
      out.write("              >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"navbar-nav\">\r\n");
      out.write("              <div class=\"user-profile\">\r\n");
      out.write("                <div class=\"user-photo\">\r\n");
      out.write("                  <a href=\"./user.html\">\r\n");
      out.write("                  \r\n");
      out.write("                   <img src=\"");
      out.print( session.getAttribute("foto") );
      out.write("\" />\r\n");
      out.write("                  </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"user-info\">\r\n");
      out.write("                  <h3>Olá, ");
      out.print( session.getAttribute("name") );
      out.write("!</h3>\r\n");
      out.write("                  <p>Bem vindo</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main class=\"d-flex justify-content-center flex-column\">\r\n");
      out.write("      <div class=\"d-flex align-items-center my-3 flex-column\">\r\n");
      out.write("        <img\r\n");
      out.write("		  src=\"");
      out.print( session.getAttribute("foto") );
      out.write("\"\r\n");
      out.write("          class=\"rounded-circle img-perfil\"\r\n");
      out.write("          id=\"\"\r\n");
      out.write("          alt=\"...\"\r\n");
      out.write("        />\r\n");
      out.write("        <p class=\"text-center text-white fs-4 mt-3 mb-2\">Olá, ");
      out.print( session.getAttribute("name") );
      out.write("!</p>\r\n");
      out.write("        <button\r\n");
      out.write("          type=\"button\"\r\n");
      out.write("          class=\"btn btn-success btn-primary fs-5 md:btn-lg\"\r\n");
      out.write("          data-bs-toggle=\"modal\"\r\n");
      out.write("          data-bs-target=\"#staticBackdrop\"\r\n");
      out.write("        >\r\n");
      out.write("          Editar Perfil\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- <div class=\"d-flex justify-content-center text-white\">\r\n");
      out.write("      <p>Olá, Roberta!</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex justify-content-center\">\r\n");
      out.write("      <button type=\"button\" class=\"btn btn-success btn-primary\" data-bs-toggle=\"modal\"\r\n");
      out.write("        data-bs-target=\"#staticBackdrop\">Editar Perfil</button>\r\n");
      out.write("    </div> -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"d-flex justify-content-center my-4\">\r\n");
      out.write("        <div class=\"card bg-dark text-white\" style=\"width: 18rem\">\r\n");
      out.write("          <ul class=\"list-group list-group-flush\">\r\n");
      out.write("            <li class=\"list-group-item text-white bg-dark\">Configure</li>\r\n");
      out.write("            <li class=\"list-group-item text-white bg-dark\">\r\n");
      out.write("              <i class=\"bi bi-bar-chart-fill text-secondary me-3 fs-4\"></i\r\n");
      out.write("              >Relatórios\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-group-item text-white bg-dark\">\r\n");
      out.write("              <i class=\"bi bi-box-arrow-left text-secondary me-3 fs-4\"></i>Sair\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"d-flex justify-content-center mb-4\">\r\n");
      out.write("        <div\r\n");
      out.write("          class=\"card bg-dark text-center text-white align-middle line-card\"\r\n");
      out.write("          style=\"width: 18rem\"\r\n");
      out.write("        >\r\n");
      out.write("          <div class=\"d-flex justify-content-center\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"d-flex justify-content-center my-3 bg-white rounded-circle\"\r\n");
      out.write("              style=\"width: 100px; height: 100px\"\r\n");
      out.write("            >\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"../img/icons/ballon-chat-icon.svg\"\r\n");
      out.write("                alt=\"\"\r\n");
      out.write("                class=\"my-auto text-dark\"\r\n");
      out.write("                style=\"width: 50%; height: 50%\"\r\n");
      out.write("              />\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h5 class=\"card-title fs-3 fw-bold\">Como podemos te ajudar?</h5>\r\n");
      out.write("            <p\r\n");
      out.write("              class=\"card-text fs-6 fw-light text-break\"\r\n");
      out.write("              style=\"color: rgb(224, 224, 224)\"\r\n");
      out.write("            >\r\n");
      out.write("              Se você está com alguma dúvida ou está com algum problema é só\r\n");
      out.write("              entrar em contato que a gente te ajuda!\r\n");
      out.write("            </p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-flex flex-row\">\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"card text-center mx-2 bg-dark text-white line-card\"\r\n");
      out.write("                style=\"width: 8rem; height: 8rem\"\r\n");
      out.write("              >\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <img\r\n");
      out.write("                    src=\"../img/icons/info-circle.svg\"\r\n");
      out.write("                    alt=\"\"\r\n");
      out.write("                    class=\"\"\r\n");
      out.write("                    style=\"width: 1.8rem; height: 1.8rem\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <p class=\"fs-6 fw-light\">Central de ajuda</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"card text-center mx-2 bg-dark text-white line-card\"\r\n");
      out.write("                style=\"width: 8rem; height: 8rem\"\r\n");
      out.write("              >\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                  <img\r\n");
      out.write("                    src=\"../img/icons/envelope.svg\"\r\n");
      out.write("                    alt=\"\"\r\n");
      out.write("                    class=\"\"\r\n");
      out.write("                    style=\"width: 1.8rem; height: 1.8rem\"\r\n");
      out.write("                  />\r\n");
      out.write("                  <p class=\"fs-6 fw-light\">Converse com a gente</p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"text-center text-white\" id=\"contato\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <section>\r\n");
      out.write("          <!-- Linkedin -->\r\n");
      out.write("          <a\r\n");
      out.write("            class=\"btn btn-floating m-1\"\r\n");
      out.write("            href=\"https://www.linkedin.com/in/gabriela-coliveira/\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("            role=\"button\"\r\n");
      out.write("            ><img src=\"../img/icons/linkedin.svg\" width=\"40\" height=\"40\"\r\n");
      out.write("          /></a>\r\n");
      out.write("\r\n");
      out.write("          <!-- Github -->\r\n");
      out.write("          <a\r\n");
      out.write("            class=\"btn btn-floating m-1\"\r\n");
      out.write("            href=\"https://github.com/GabiCmg\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("            role=\"button\"\r\n");
      out.write("            ><img src=\"../img/icons/github.svg\" width=\"40\" height=\"40\"\r\n");
      out.write("          /></a>\r\n");
      out.write("        </section>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.2)\">\r\n");
      out.write("        © 2022 Copyright: GabiCmg\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <!-- MODAL -->\r\n");
      out.write("\r\n");
      out.write("    <div\r\n");
      out.write("      class=\"modal fade\"\r\n");
      out.write("      id=\"staticBackdrop\"\r\n");
      out.write("      data-bs-backdrop=\"static\"\r\n");
      out.write("      data-bs-keyboard=\"false\"\r\n");
      out.write("      tabindex=\"-1\"\r\n");
      out.write("      aria-labelledby=\"staticBackdropLabel\"\r\n");
      out.write("      aria-hidden=\"true\"\r\n");
      out.write("    >\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content bg-dark text-white\">\r\n");
      out.write("          <div class=\"modal-header border-secondary\">\r\n");
      out.write("            <h1 class=\"modal-title fs-5\" id=\"staticBackdropLabel\">\r\n");
      out.write("              Editar Perfil\r\n");
      out.write("            </h1>\r\n");
      out.write("            <button\r\n");
      out.write("              type=\"button\"\r\n");
      out.write("              class=\"btn-close bg-light\"\r\n");
      out.write("              data-bs-dismiss=\"modal\"\r\n");
      out.write("              aria-label=\"Close\"\r\n");
      out.write("            ></button>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("              <div class=\"mb-3\">\r\n");
      out.write("                <div class=\"d-flex justify-content-center my-3\">\r\n");
      out.write("                  <img\r\n");
      out.write("                    src=\"../img/user.png\"\r\n");
      out.write("                    class=\"rounded-circle\"\r\n");
      out.write("                    alt=\"...\"\r\n");
      out.write("                    style=\"width: 8rem; height: 8rem\"\r\n");
      out.write("                  />\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <div class=\"mx-5\">\r\n");
      out.write("                <img src=\"../img/icons/pencil-square.svg\" alt=\"\" class=\"\" style=\"width: 1.4rem; height: 1.4rem;\">\r\n");
      out.write("              </div> -->\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"input-group mb-3 mx-4 w-auto bg-dark\">\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"file\"\r\n");
      out.write("                  class=\"form-control bg-dark border-secondary text-light\"\r\n");
      out.write("                  id=\"inputGroupFile02\"\r\n");
      out.write("                />\r\n");
      out.write("                <label\r\n");
      out.write("                  class=\"input-group-text bg-dark border-secondary text-light\"\r\n");
      out.write("                  for=\"inputGroupFile02\"\r\n");
      out.write("                  >Upload</label\r\n");
      out.write("                >\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"mb-3 mx-4\">\r\n");
      out.write("                <label for=\"exampleFormControlInput1\" class=\"form-label\"\r\n");
      out.write("                  >E-mail</label\r\n");
      out.write("                >\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"email\"\r\n");
      out.write("                  class=\"form-control bg-dark border-secondary text-light\"\r\n");
      out.write("                  id=\"exampleFormControlInput1\"\r\n");
      out.write("                  placeholder=\"name@example.com\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"mb-3 mx-4\">\r\n");
      out.write("                <label for=\"exampleFormControlInput1\" class=\"form-label\"\r\n");
      out.write("                  >Senha</label\r\n");
      out.write("                >\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"password\"\r\n");
      out.write("                  class=\"form-control bg-dark border-secondary text-light\"\r\n");
      out.write("                  id=\"inputPassword6\"\r\n");
      out.write("                  aria-describedby=\"passwordHelpInline\"\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"mb-3 mx-4\">\r\n");
      out.write("                <label for=\"exampleFormControlInput1\" class=\"form-label\"\r\n");
      out.write("                  >Confirmar Senha</label\r\n");
      out.write("                >\r\n");
      out.write("                <input\r\n");
      out.write("                  type=\"password\"\r\n");
      out.write("                  class=\"form-control bg-dark border-secondary text-light\"\r\n");
      out.write("                  id=\"inputPassword6\"\r\n");
      out.write("                  aria-describedby=\"passwordHelpInline\"\r\n");
      out.write("                  required\r\n");
      out.write("                />\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-footer border-secondary\">\r\n");
      out.write("            <button\r\n");
      out.write("              type=\"button\"\r\n");
      out.write("              class=\"btn btn-secondary\"\r\n");
      out.write("              data-bs-dismiss=\"modal\"\r\n");
      out.write("            >\r\n");
      out.write("              Fechar\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("              type=\"submit\"\r\n");
      out.write("              class=\"btn btn-primary bg-success border-success\"\r\n");
      out.write("            >\r\n");
      out.write("              Salvar Alterações\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
